name: coastal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=20
  - ipykernel <6.21 # until https://github.com/dask/distributed/issues/7515 is solved
  - ipywidgets #  ipywidgets here and jupyterlab_widgets in jupyterlab env
  - ipyleaflet
  - matplotlib
  - jupyter notebook
  - xarray
  - pandas
